[#-- @ftlvariable name="repository" type="com.atlassian.bamboo.plugins.git.GitRepository" --]
[@s.checkbox labelKey='repository.github.useSubmodules' name='repository.github.useSubmodules' /]
[@s.textfield labelKey='repository.github.commandTimeout' name='repository.github.commandTimeout' /]
[@s.checkbox labelKey='repository.github.verbose.logs' name='repository.github.verbose.logs' /]
[@s.checkbox labelKey='repository.github.fetch.whole.repository' name='repository.github.fetch.whole.repository' /]
